# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle

# Target Git Branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # Host Runner
    runs-on: ubuntu-latest
    # Java Image
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build && ls -la ./build/libs/

  delpoy:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Upload file to S3
      env: 
        S3_UPLOAD_BUCKET: ${{ secrets.S3_UPLOAD_BUCKET }}
      run: |
         aws s3 cp ./build/libs/*.jar s3://$S3_UPLOAD_BUCKET/ --quiet
      needs: build
